apiVersion: v1
kind: Service # Tipo do objeto, no caso, um Service
metadata:
  name: nginx
spec:
  selector: # Seleciona os Pods que serão expostos pelo Service
    app: nginx # Neste caso, os Pods com o label app=meu-app
  ports:
    - protocol: TCP
      port: 80 # Porta do Service
      targetPort: 80 # Porta dos Pods
  type: ClusterIP
